twilio: # Twilio gateway configuration
  accountId: AC1bf7e808179af182f6849a9def06831d
  accountToken: f6936c074e377af39d393d29e6326ca6
  numbers: [+19163474456]
  messagingServicesId:
  localDomain: localhost

push:
  queueSize: 20 # Size of push pending queue

turn: # TURN server configuration
  secret: test
  uris: ["turn:localhost:40968"]

cache:
  url: "redis://localhost:6379/1"
  replicaUrls:
  - "redis://localhost:6379/3"

pushScheduler:
  url: "redis://localhost:6379/6"
  replicaUrls:
  - "redis://localhost:6379/8"

messageCache:
  redis: {
    url: "redis://localhost:6379/9",
    replicaUrls: ["redis://localhost:6379/10"]
  }
  cacheRate: 1
  persistDelayMinutes: 10

directory:
  url: "redis://localhost:6379/0"
  replicaUrls:
  - "redis://localhost:6379/4"

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "password"
  url: "jdbc:postgresql://localhost:5432/messagedb"

attachments: # AWS S3 configuration
  accessKey: ABCDEFGCUFYDHVM2LXXX
  accessSecret: W0UfGDddfAbqYyCTIIbSQlDtreTGokOs0OTpL0SE
  bucket: byuisrlsignalserverrforresearch

profiles: # AWS S3 configuration
  accessKey: ABCDEFGCUFYDHVM2LXXX
  accessSecret: W0UfGDddfAbqYyCTIIbSQlDtreTGokOs0OTpL0SE
  bucket: byuisrlsignalserverrforresearch
  region: eu-west-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "password"
  url: "jdbc:postgresql://localhost:5432/accountsdb"

apn: # Apple Push Notifications configuration
  bundleId: Cdsjalfksjdlfkjsdlfksdlfkjsdfkjas
  pushCertificate: Cdsjalfksjdlfkjsdlfksdlfkjsdfkjas
  pushKey: Cdsjalfksjdlfkjsdlfksdlfkjsdfkjas

gcm: # GCM Configuration
  senderId: 675527209655
  apiKey: AAAAnUiPMrc:APA91bFnxHhHM_SUug2p_GETC6PdwC6XvWtHRdN4B7r_5IYAvo-FKsq6a-HMQxNLpuNihfKIJxXT1-4PpBAMC3-T5ViFg24ZVF-v9x_Ie2CV6wfHJVBEQJElBtypLCDf8qlNUqOJxJWl

server:
  applicationConnectors:
  - type: https
    port: 8082
    keyStorePath: keygen/keystore.jks
    keyStorePassword: password
    validateCerts: false
  - type: http
    port: 8081
  adminConnectors:
  - type: http
    port: 8083

# BYU ISRL!
mitmAttack:
  # conversation is two phone numbers concatenated with a _ between them. (Exp. "+15555555555_+16666666666")
  targetedConversations: ["+12222222222_+13333333333"]
  targetedUsers: []

impersonationAttack:
  # conversation is two phone numbers concatenated with a _ between them. (Exp. "+15555555555_+16666666666")
  targetedConversations: []
  targetedUsers: []
  foward: "+18888888888"