// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_admin_api.proto

package com.google.trillian.proto;

public interface DeleteTreeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.DeleteTreeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the tree to delete.
   * </pre>
   *
   * <code>int64 tree_id = 1;</code>
   */
  long getTreeId();
}
