// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_log_api.proto

package com.google.trillian.proto;

/**
 * Protobuf type {@code trillian.GetLeavesByHashResponse}
 */
public  final class GetLeavesByHashResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trillian.GetLeavesByHashResponse)
    GetLeavesByHashResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLeavesByHashResponse.newBuilder() to construct.
  private GetLeavesByHashResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLeavesByHashResponse() {
    leaves_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLeavesByHashResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              leaves_ = new java.util.ArrayList<com.google.trillian.proto.LogLeaf>();
              mutable_bitField0_ |= 0x00000001;
            }
            leaves_.add(
                input.readMessage(com.google.trillian.proto.LogLeaf.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.google.trillian.proto.SignedLogRoot.Builder subBuilder = null;
            if (signedLogRoot_ != null) {
              subBuilder = signedLogRoot_.toBuilder();
            }
            signedLogRoot_ = input.readMessage(com.google.trillian.proto.SignedLogRoot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(signedLogRoot_);
              signedLogRoot_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        leaves_ = java.util.Collections.unmodifiableList(leaves_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLeavesByHashResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLeavesByHashResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.trillian.proto.GetLeavesByHashResponse.class, com.google.trillian.proto.GetLeavesByHashResponse.Builder.class);
  }

  private int bitField0_;
  public static final int LEAVES_FIELD_NUMBER = 2;
  private java.util.List<com.google.trillian.proto.LogLeaf> leaves_;
  /**
   * <code>repeated .trillian.LogLeaf leaves = 2;</code>
   */
  public java.util.List<com.google.trillian.proto.LogLeaf> getLeavesList() {
    return leaves_;
  }
  /**
   * <code>repeated .trillian.LogLeaf leaves = 2;</code>
   */
  public java.util.List<? extends com.google.trillian.proto.LogLeafOrBuilder> 
      getLeavesOrBuilderList() {
    return leaves_;
  }
  /**
   * <code>repeated .trillian.LogLeaf leaves = 2;</code>
   */
  public int getLeavesCount() {
    return leaves_.size();
  }
  /**
   * <code>repeated .trillian.LogLeaf leaves = 2;</code>
   */
  public com.google.trillian.proto.LogLeaf getLeaves(int index) {
    return leaves_.get(index);
  }
  /**
   * <code>repeated .trillian.LogLeaf leaves = 2;</code>
   */
  public com.google.trillian.proto.LogLeafOrBuilder getLeavesOrBuilder(
      int index) {
    return leaves_.get(index);
  }

  public static final int SIGNED_LOG_ROOT_FIELD_NUMBER = 3;
  private com.google.trillian.proto.SignedLogRoot signedLogRoot_;
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
   */
  public boolean hasSignedLogRoot() {
    return signedLogRoot_ != null;
  }
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
   */
  public com.google.trillian.proto.SignedLogRoot getSignedLogRoot() {
    return signedLogRoot_ == null ? com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
  }
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
   */
  public com.google.trillian.proto.SignedLogRootOrBuilder getSignedLogRootOrBuilder() {
    return getSignedLogRoot();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < leaves_.size(); i++) {
      output.writeMessage(2, leaves_.get(i));
    }
    if (signedLogRoot_ != null) {
      output.writeMessage(3, getSignedLogRoot());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < leaves_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, leaves_.get(i));
    }
    if (signedLogRoot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSignedLogRoot());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.trillian.proto.GetLeavesByHashResponse)) {
      return super.equals(obj);
    }
    com.google.trillian.proto.GetLeavesByHashResponse other = (com.google.trillian.proto.GetLeavesByHashResponse) obj;

    boolean result = true;
    result = result && getLeavesList()
        .equals(other.getLeavesList());
    result = result && (hasSignedLogRoot() == other.hasSignedLogRoot());
    if (hasSignedLogRoot()) {
      result = result && getSignedLogRoot()
          .equals(other.getSignedLogRoot());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLeavesCount() > 0) {
      hash = (37 * hash) + LEAVES_FIELD_NUMBER;
      hash = (53 * hash) + getLeavesList().hashCode();
    }
    if (hasSignedLogRoot()) {
      hash = (37 * hash) + SIGNED_LOG_ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getSignedLogRoot().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLeavesByHashResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.GetLeavesByHashResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trillian.GetLeavesByHashResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.GetLeavesByHashResponse)
      com.google.trillian.proto.GetLeavesByHashResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLeavesByHashResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLeavesByHashResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.trillian.proto.GetLeavesByHashResponse.class, com.google.trillian.proto.GetLeavesByHashResponse.Builder.class);
    }

    // Construct using com.google.trillian.proto.GetLeavesByHashResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLeavesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (leavesBuilder_ == null) {
        leaves_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        leavesBuilder_.clear();
      }
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = null;
      } else {
        signedLogRoot_ = null;
        signedLogRootBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLeavesByHashResponse_descriptor;
    }

    public com.google.trillian.proto.GetLeavesByHashResponse getDefaultInstanceForType() {
      return com.google.trillian.proto.GetLeavesByHashResponse.getDefaultInstance();
    }

    public com.google.trillian.proto.GetLeavesByHashResponse build() {
      com.google.trillian.proto.GetLeavesByHashResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.trillian.proto.GetLeavesByHashResponse buildPartial() {
      com.google.trillian.proto.GetLeavesByHashResponse result = new com.google.trillian.proto.GetLeavesByHashResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (leavesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          leaves_ = java.util.Collections.unmodifiableList(leaves_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.leaves_ = leaves_;
      } else {
        result.leaves_ = leavesBuilder_.build();
      }
      if (signedLogRootBuilder_ == null) {
        result.signedLogRoot_ = signedLogRoot_;
      } else {
        result.signedLogRoot_ = signedLogRootBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.trillian.proto.GetLeavesByHashResponse) {
        return mergeFrom((com.google.trillian.proto.GetLeavesByHashResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.trillian.proto.GetLeavesByHashResponse other) {
      if (other == com.google.trillian.proto.GetLeavesByHashResponse.getDefaultInstance()) return this;
      if (leavesBuilder_ == null) {
        if (!other.leaves_.isEmpty()) {
          if (leaves_.isEmpty()) {
            leaves_ = other.leaves_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLeavesIsMutable();
            leaves_.addAll(other.leaves_);
          }
          onChanged();
        }
      } else {
        if (!other.leaves_.isEmpty()) {
          if (leavesBuilder_.isEmpty()) {
            leavesBuilder_.dispose();
            leavesBuilder_ = null;
            leaves_ = other.leaves_;
            bitField0_ = (bitField0_ & ~0x00000001);
            leavesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLeavesFieldBuilder() : null;
          } else {
            leavesBuilder_.addAllMessages(other.leaves_);
          }
        }
      }
      if (other.hasSignedLogRoot()) {
        mergeSignedLogRoot(other.getSignedLogRoot());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.trillian.proto.GetLeavesByHashResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.trillian.proto.GetLeavesByHashResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.trillian.proto.LogLeaf> leaves_ =
      java.util.Collections.emptyList();
    private void ensureLeavesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        leaves_ = new java.util.ArrayList<com.google.trillian.proto.LogLeaf>(leaves_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.trillian.proto.LogLeaf, com.google.trillian.proto.LogLeaf.Builder, com.google.trillian.proto.LogLeafOrBuilder> leavesBuilder_;

    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public java.util.List<com.google.trillian.proto.LogLeaf> getLeavesList() {
      if (leavesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(leaves_);
      } else {
        return leavesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public int getLeavesCount() {
      if (leavesBuilder_ == null) {
        return leaves_.size();
      } else {
        return leavesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public com.google.trillian.proto.LogLeaf getLeaves(int index) {
      if (leavesBuilder_ == null) {
        return leaves_.get(index);
      } else {
        return leavesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder setLeaves(
        int index, com.google.trillian.proto.LogLeaf value) {
      if (leavesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLeavesIsMutable();
        leaves_.set(index, value);
        onChanged();
      } else {
        leavesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder setLeaves(
        int index, com.google.trillian.proto.LogLeaf.Builder builderForValue) {
      if (leavesBuilder_ == null) {
        ensureLeavesIsMutable();
        leaves_.set(index, builderForValue.build());
        onChanged();
      } else {
        leavesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder addLeaves(com.google.trillian.proto.LogLeaf value) {
      if (leavesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLeavesIsMutable();
        leaves_.add(value);
        onChanged();
      } else {
        leavesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder addLeaves(
        int index, com.google.trillian.proto.LogLeaf value) {
      if (leavesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLeavesIsMutable();
        leaves_.add(index, value);
        onChanged();
      } else {
        leavesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder addLeaves(
        com.google.trillian.proto.LogLeaf.Builder builderForValue) {
      if (leavesBuilder_ == null) {
        ensureLeavesIsMutable();
        leaves_.add(builderForValue.build());
        onChanged();
      } else {
        leavesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder addLeaves(
        int index, com.google.trillian.proto.LogLeaf.Builder builderForValue) {
      if (leavesBuilder_ == null) {
        ensureLeavesIsMutable();
        leaves_.add(index, builderForValue.build());
        onChanged();
      } else {
        leavesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder addAllLeaves(
        java.lang.Iterable<? extends com.google.trillian.proto.LogLeaf> values) {
      if (leavesBuilder_ == null) {
        ensureLeavesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, leaves_);
        onChanged();
      } else {
        leavesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder clearLeaves() {
      if (leavesBuilder_ == null) {
        leaves_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        leavesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public Builder removeLeaves(int index) {
      if (leavesBuilder_ == null) {
        ensureLeavesIsMutable();
        leaves_.remove(index);
        onChanged();
      } else {
        leavesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public com.google.trillian.proto.LogLeaf.Builder getLeavesBuilder(
        int index) {
      return getLeavesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public com.google.trillian.proto.LogLeafOrBuilder getLeavesOrBuilder(
        int index) {
      if (leavesBuilder_ == null) {
        return leaves_.get(index);  } else {
        return leavesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public java.util.List<? extends com.google.trillian.proto.LogLeafOrBuilder> 
         getLeavesOrBuilderList() {
      if (leavesBuilder_ != null) {
        return leavesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(leaves_);
      }
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public com.google.trillian.proto.LogLeaf.Builder addLeavesBuilder() {
      return getLeavesFieldBuilder().addBuilder(
          com.google.trillian.proto.LogLeaf.getDefaultInstance());
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public com.google.trillian.proto.LogLeaf.Builder addLeavesBuilder(
        int index) {
      return getLeavesFieldBuilder().addBuilder(
          index, com.google.trillian.proto.LogLeaf.getDefaultInstance());
    }
    /**
     * <code>repeated .trillian.LogLeaf leaves = 2;</code>
     */
    public java.util.List<com.google.trillian.proto.LogLeaf.Builder> 
         getLeavesBuilderList() {
      return getLeavesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.trillian.proto.LogLeaf, com.google.trillian.proto.LogLeaf.Builder, com.google.trillian.proto.LogLeafOrBuilder> 
        getLeavesFieldBuilder() {
      if (leavesBuilder_ == null) {
        leavesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.trillian.proto.LogLeaf, com.google.trillian.proto.LogLeaf.Builder, com.google.trillian.proto.LogLeafOrBuilder>(
                leaves_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        leaves_ = null;
      }
      return leavesBuilder_;
    }

    private com.google.trillian.proto.SignedLogRoot signedLogRoot_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder> signedLogRootBuilder_;
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public boolean hasSignedLogRoot() {
      return signedLogRootBuilder_ != null || signedLogRoot_ != null;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public com.google.trillian.proto.SignedLogRoot getSignedLogRoot() {
      if (signedLogRootBuilder_ == null) {
        return signedLogRoot_ == null ? com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
      } else {
        return signedLogRootBuilder_.getMessage();
      }
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public Builder setSignedLogRoot(com.google.trillian.proto.SignedLogRoot value) {
      if (signedLogRootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signedLogRoot_ = value;
        onChanged();
      } else {
        signedLogRootBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public Builder setSignedLogRoot(
        com.google.trillian.proto.SignedLogRoot.Builder builderForValue) {
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = builderForValue.build();
        onChanged();
      } else {
        signedLogRootBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public Builder mergeSignedLogRoot(com.google.trillian.proto.SignedLogRoot value) {
      if (signedLogRootBuilder_ == null) {
        if (signedLogRoot_ != null) {
          signedLogRoot_ =
            com.google.trillian.proto.SignedLogRoot.newBuilder(signedLogRoot_).mergeFrom(value).buildPartial();
        } else {
          signedLogRoot_ = value;
        }
        onChanged();
      } else {
        signedLogRootBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public Builder clearSignedLogRoot() {
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = null;
        onChanged();
      } else {
        signedLogRoot_ = null;
        signedLogRootBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public com.google.trillian.proto.SignedLogRoot.Builder getSignedLogRootBuilder() {
      
      onChanged();
      return getSignedLogRootFieldBuilder().getBuilder();
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    public com.google.trillian.proto.SignedLogRootOrBuilder getSignedLogRootOrBuilder() {
      if (signedLogRootBuilder_ != null) {
        return signedLogRootBuilder_.getMessageOrBuilder();
      } else {
        return signedLogRoot_ == null ?
            com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
      }
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder> 
        getSignedLogRootFieldBuilder() {
      if (signedLogRootBuilder_ == null) {
        signedLogRootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder>(
                getSignedLogRoot(),
                getParentForChildren(),
                isClean());
        signedLogRoot_ = null;
      }
      return signedLogRootBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trillian.GetLeavesByHashResponse)
  }

  // @@protoc_insertion_point(class_scope:trillian.GetLeavesByHashResponse)
  private static final com.google.trillian.proto.GetLeavesByHashResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.trillian.proto.GetLeavesByHashResponse();
  }

  public static com.google.trillian.proto.GetLeavesByHashResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLeavesByHashResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLeavesByHashResponse>() {
    public GetLeavesByHashResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLeavesByHashResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLeavesByHashResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLeavesByHashResponse> getParserForType() {
    return PARSER;
  }

  public com.google.trillian.proto.GetLeavesByHashResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

