// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_log_api.proto

package com.google.trillian.proto;

public interface GetLeavesByIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetLeavesByIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 log_id = 1;</code>
   */
  long getLogId();

  /**
   * <code>repeated int64 leaf_index = 2;</code>
   */
  java.util.List<java.lang.Long> getLeafIndexList();
  /**
   * <code>repeated int64 leaf_index = 2;</code>
   */
  int getLeafIndexCount();
  /**
   * <code>repeated int64 leaf_index = 2;</code>
   */
  long getLeafIndex(int index);

  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  boolean hasChargeTo();
  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  com.google.trillian.proto.ChargeTo getChargeTo();
  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  com.google.trillian.proto.ChargeToOrBuilder getChargeToOrBuilder();
}
