// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_log_api.proto

package com.google.trillian.proto;

/**
 * Protobuf type {@code trillian.GetLatestSignedLogRootResponse}
 */
public  final class GetLatestSignedLogRootResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trillian.GetLatestSignedLogRootResponse)
    GetLatestSignedLogRootResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLatestSignedLogRootResponse.newBuilder() to construct.
  private GetLatestSignedLogRootResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLatestSignedLogRootResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLatestSignedLogRootResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            com.google.trillian.proto.SignedLogRoot.Builder subBuilder = null;
            if (signedLogRoot_ != null) {
              subBuilder = signedLogRoot_.toBuilder();
            }
            signedLogRoot_ = input.readMessage(com.google.trillian.proto.SignedLogRoot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(signedLogRoot_);
              signedLogRoot_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.trillian.proto.Proof.Builder subBuilder = null;
            if (proof_ != null) {
              subBuilder = proof_.toBuilder();
            }
            proof_ = input.readMessage(com.google.trillian.proto.Proof.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(proof_);
              proof_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLatestSignedLogRootResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLatestSignedLogRootResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.trillian.proto.GetLatestSignedLogRootResponse.class, com.google.trillian.proto.GetLatestSignedLogRootResponse.Builder.class);
  }

  public static final int SIGNED_LOG_ROOT_FIELD_NUMBER = 2;
  private com.google.trillian.proto.SignedLogRoot signedLogRoot_;
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
   */
  public boolean hasSignedLogRoot() {
    return signedLogRoot_ != null;
  }
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
   */
  public com.google.trillian.proto.SignedLogRoot getSignedLogRoot() {
    return signedLogRoot_ == null ? com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
  }
  /**
   * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
   */
  public com.google.trillian.proto.SignedLogRootOrBuilder getSignedLogRootOrBuilder() {
    return getSignedLogRoot();
  }

  public static final int PROOF_FIELD_NUMBER = 3;
  private com.google.trillian.proto.Proof proof_;
  /**
   * <pre>
   * proof is filled in with a consistency proof if first_tree_size in
   * GetLatestSignedLogRootRequest is non-zero (and within the tree size
   * available at the server).
   * </pre>
   *
   * <code>.trillian.Proof proof = 3;</code>
   */
  public boolean hasProof() {
    return proof_ != null;
  }
  /**
   * <pre>
   * proof is filled in with a consistency proof if first_tree_size in
   * GetLatestSignedLogRootRequest is non-zero (and within the tree size
   * available at the server).
   * </pre>
   *
   * <code>.trillian.Proof proof = 3;</code>
   */
  public com.google.trillian.proto.Proof getProof() {
    return proof_ == null ? com.google.trillian.proto.Proof.getDefaultInstance() : proof_;
  }
  /**
   * <pre>
   * proof is filled in with a consistency proof if first_tree_size in
   * GetLatestSignedLogRootRequest is non-zero (and within the tree size
   * available at the server).
   * </pre>
   *
   * <code>.trillian.Proof proof = 3;</code>
   */
  public com.google.trillian.proto.ProofOrBuilder getProofOrBuilder() {
    return getProof();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (signedLogRoot_ != null) {
      output.writeMessage(2, getSignedLogRoot());
    }
    if (proof_ != null) {
      output.writeMessage(3, getProof());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (signedLogRoot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSignedLogRoot());
    }
    if (proof_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProof());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.trillian.proto.GetLatestSignedLogRootResponse)) {
      return super.equals(obj);
    }
    com.google.trillian.proto.GetLatestSignedLogRootResponse other = (com.google.trillian.proto.GetLatestSignedLogRootResponse) obj;

    boolean result = true;
    result = result && (hasSignedLogRoot() == other.hasSignedLogRoot());
    if (hasSignedLogRoot()) {
      result = result && getSignedLogRoot()
          .equals(other.getSignedLogRoot());
    }
    result = result && (hasProof() == other.hasProof());
    if (hasProof()) {
      result = result && getProof()
          .equals(other.getProof());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSignedLogRoot()) {
      hash = (37 * hash) + SIGNED_LOG_ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getSignedLogRoot().hashCode();
    }
    if (hasProof()) {
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.GetLatestSignedLogRootResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.GetLatestSignedLogRootResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trillian.GetLatestSignedLogRootResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.GetLatestSignedLogRootResponse)
      com.google.trillian.proto.GetLatestSignedLogRootResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLatestSignedLogRootResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLatestSignedLogRootResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.trillian.proto.GetLatestSignedLogRootResponse.class, com.google.trillian.proto.GetLatestSignedLogRootResponse.Builder.class);
    }

    // Construct using com.google.trillian.proto.GetLatestSignedLogRootResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = null;
      } else {
        signedLogRoot_ = null;
        signedLogRootBuilder_ = null;
      }
      if (proofBuilder_ == null) {
        proof_ = null;
      } else {
        proof_ = null;
        proofBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_GetLatestSignedLogRootResponse_descriptor;
    }

    public com.google.trillian.proto.GetLatestSignedLogRootResponse getDefaultInstanceForType() {
      return com.google.trillian.proto.GetLatestSignedLogRootResponse.getDefaultInstance();
    }

    public com.google.trillian.proto.GetLatestSignedLogRootResponse build() {
      com.google.trillian.proto.GetLatestSignedLogRootResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.trillian.proto.GetLatestSignedLogRootResponse buildPartial() {
      com.google.trillian.proto.GetLatestSignedLogRootResponse result = new com.google.trillian.proto.GetLatestSignedLogRootResponse(this);
      if (signedLogRootBuilder_ == null) {
        result.signedLogRoot_ = signedLogRoot_;
      } else {
        result.signedLogRoot_ = signedLogRootBuilder_.build();
      }
      if (proofBuilder_ == null) {
        result.proof_ = proof_;
      } else {
        result.proof_ = proofBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.trillian.proto.GetLatestSignedLogRootResponse) {
        return mergeFrom((com.google.trillian.proto.GetLatestSignedLogRootResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.trillian.proto.GetLatestSignedLogRootResponse other) {
      if (other == com.google.trillian.proto.GetLatestSignedLogRootResponse.getDefaultInstance()) return this;
      if (other.hasSignedLogRoot()) {
        mergeSignedLogRoot(other.getSignedLogRoot());
      }
      if (other.hasProof()) {
        mergeProof(other.getProof());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.trillian.proto.GetLatestSignedLogRootResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.trillian.proto.GetLatestSignedLogRootResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.trillian.proto.SignedLogRoot signedLogRoot_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder> signedLogRootBuilder_;
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public boolean hasSignedLogRoot() {
      return signedLogRootBuilder_ != null || signedLogRoot_ != null;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public com.google.trillian.proto.SignedLogRoot getSignedLogRoot() {
      if (signedLogRootBuilder_ == null) {
        return signedLogRoot_ == null ? com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
      } else {
        return signedLogRootBuilder_.getMessage();
      }
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public Builder setSignedLogRoot(com.google.trillian.proto.SignedLogRoot value) {
      if (signedLogRootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signedLogRoot_ = value;
        onChanged();
      } else {
        signedLogRootBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public Builder setSignedLogRoot(
        com.google.trillian.proto.SignedLogRoot.Builder builderForValue) {
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = builderForValue.build();
        onChanged();
      } else {
        signedLogRootBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public Builder mergeSignedLogRoot(com.google.trillian.proto.SignedLogRoot value) {
      if (signedLogRootBuilder_ == null) {
        if (signedLogRoot_ != null) {
          signedLogRoot_ =
            com.google.trillian.proto.SignedLogRoot.newBuilder(signedLogRoot_).mergeFrom(value).buildPartial();
        } else {
          signedLogRoot_ = value;
        }
        onChanged();
      } else {
        signedLogRootBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public Builder clearSignedLogRoot() {
      if (signedLogRootBuilder_ == null) {
        signedLogRoot_ = null;
        onChanged();
      } else {
        signedLogRoot_ = null;
        signedLogRootBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public com.google.trillian.proto.SignedLogRoot.Builder getSignedLogRootBuilder() {
      
      onChanged();
      return getSignedLogRootFieldBuilder().getBuilder();
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    public com.google.trillian.proto.SignedLogRootOrBuilder getSignedLogRootOrBuilder() {
      if (signedLogRootBuilder_ != null) {
        return signedLogRootBuilder_.getMessageOrBuilder();
      } else {
        return signedLogRoot_ == null ?
            com.google.trillian.proto.SignedLogRoot.getDefaultInstance() : signedLogRoot_;
      }
    }
    /**
     * <code>.trillian.SignedLogRoot signed_log_root = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder> 
        getSignedLogRootFieldBuilder() {
      if (signedLogRootBuilder_ == null) {
        signedLogRootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.trillian.proto.SignedLogRoot, com.google.trillian.proto.SignedLogRoot.Builder, com.google.trillian.proto.SignedLogRootOrBuilder>(
                getSignedLogRoot(),
                getParentForChildren(),
                isClean());
        signedLogRoot_ = null;
      }
      return signedLogRootBuilder_;
    }

    private com.google.trillian.proto.Proof proof_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.Proof, com.google.trillian.proto.Proof.Builder, com.google.trillian.proto.ProofOrBuilder> proofBuilder_;
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public boolean hasProof() {
      return proofBuilder_ != null || proof_ != null;
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public com.google.trillian.proto.Proof getProof() {
      if (proofBuilder_ == null) {
        return proof_ == null ? com.google.trillian.proto.Proof.getDefaultInstance() : proof_;
      } else {
        return proofBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public Builder setProof(com.google.trillian.proto.Proof value) {
      if (proofBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proof_ = value;
        onChanged();
      } else {
        proofBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public Builder setProof(
        com.google.trillian.proto.Proof.Builder builderForValue) {
      if (proofBuilder_ == null) {
        proof_ = builderForValue.build();
        onChanged();
      } else {
        proofBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public Builder mergeProof(com.google.trillian.proto.Proof value) {
      if (proofBuilder_ == null) {
        if (proof_ != null) {
          proof_ =
            com.google.trillian.proto.Proof.newBuilder(proof_).mergeFrom(value).buildPartial();
        } else {
          proof_ = value;
        }
        onChanged();
      } else {
        proofBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public Builder clearProof() {
      if (proofBuilder_ == null) {
        proof_ = null;
        onChanged();
      } else {
        proof_ = null;
        proofBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public com.google.trillian.proto.Proof.Builder getProofBuilder() {
      
      onChanged();
      return getProofFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    public com.google.trillian.proto.ProofOrBuilder getProofOrBuilder() {
      if (proofBuilder_ != null) {
        return proofBuilder_.getMessageOrBuilder();
      } else {
        return proof_ == null ?
            com.google.trillian.proto.Proof.getDefaultInstance() : proof_;
      }
    }
    /**
     * <pre>
     * proof is filled in with a consistency proof if first_tree_size in
     * GetLatestSignedLogRootRequest is non-zero (and within the tree size
     * available at the server).
     * </pre>
     *
     * <code>.trillian.Proof proof = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.Proof, com.google.trillian.proto.Proof.Builder, com.google.trillian.proto.ProofOrBuilder> 
        getProofFieldBuilder() {
      if (proofBuilder_ == null) {
        proofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.trillian.proto.Proof, com.google.trillian.proto.Proof.Builder, com.google.trillian.proto.ProofOrBuilder>(
                getProof(),
                getParentForChildren(),
                isClean());
        proof_ = null;
      }
      return proofBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trillian.GetLatestSignedLogRootResponse)
  }

  // @@protoc_insertion_point(class_scope:trillian.GetLatestSignedLogRootResponse)
  private static final com.google.trillian.proto.GetLatestSignedLogRootResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.trillian.proto.GetLatestSignedLogRootResponse();
  }

  public static com.google.trillian.proto.GetLatestSignedLogRootResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLatestSignedLogRootResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLatestSignedLogRootResponse>() {
    public GetLatestSignedLogRootResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLatestSignedLogRootResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLatestSignedLogRootResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLatestSignedLogRootResponse> getParserForType() {
    return PARSER;
  }

  public com.google.trillian.proto.GetLatestSignedLogRootResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

