// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_log_api.proto

package com.google.trillian.proto;

public interface GetLeavesByHashRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetLeavesByHashRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 log_id = 1;</code>
   */
  long getLogId();

  /**
   * <pre>
   * The Merkle leaf hash of the leaf to be retrieved.
   * </pre>
   *
   * <code>repeated bytes leaf_hash = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getLeafHashList();
  /**
   * <pre>
   * The Merkle leaf hash of the leaf to be retrieved.
   * </pre>
   *
   * <code>repeated bytes leaf_hash = 2;</code>
   */
  int getLeafHashCount();
  /**
   * <pre>
   * The Merkle leaf hash of the leaf to be retrieved.
   * </pre>
   *
   * <code>repeated bytes leaf_hash = 2;</code>
   */
  com.google.protobuf.ByteString getLeafHash(int index);

  /**
   * <pre>
   * If order_by_sequence is set then leaves will be returned in order of ascending
   * leaf index.
   * </pre>
   *
   * <code>bool order_by_sequence = 3;</code>
   */
  boolean getOrderBySequence();

  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  boolean hasChargeTo();
  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  com.google.trillian.proto.ChargeTo getChargeTo();
  /**
   * <code>.trillian.ChargeTo charge_to = 5;</code>
   */
  com.google.trillian.proto.ChargeToOrBuilder getChargeToOrBuilder();
}
