// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_admin_api.proto

package com.google.trillian.proto;

/**
 * <pre>
 * ListTrees response.
 * No pagination is provided, all trees the requester has access to are
 * returned.
 * </pre>
 *
 * Protobuf type {@code trillian.ListTreesResponse}
 */
public  final class ListTreesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trillian.ListTreesResponse)
    ListTreesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListTreesResponse.newBuilder() to construct.
  private ListTreesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListTreesResponse() {
    tree_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListTreesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tree_ = new java.util.ArrayList<com.google.trillian.proto.Tree>();
              mutable_bitField0_ |= 0x00000001;
            }
            tree_.add(
                input.readMessage(com.google.trillian.proto.Tree.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tree_ = java.util.Collections.unmodifiableList(tree_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianAdminApiProto.internal_static_trillian_ListTreesResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.trillian.proto.TrillianAdminApiProto.internal_static_trillian_ListTreesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.trillian.proto.ListTreesResponse.class, com.google.trillian.proto.ListTreesResponse.Builder.class);
  }

  public static final int TREE_FIELD_NUMBER = 1;
  private java.util.List<com.google.trillian.proto.Tree> tree_;
  /**
   * <pre>
   * Trees matching the list request filters.
   * </pre>
   *
   * <code>repeated .trillian.Tree tree = 1;</code>
   */
  public java.util.List<com.google.trillian.proto.Tree> getTreeList() {
    return tree_;
  }
  /**
   * <pre>
   * Trees matching the list request filters.
   * </pre>
   *
   * <code>repeated .trillian.Tree tree = 1;</code>
   */
  public java.util.List<? extends com.google.trillian.proto.TreeOrBuilder> 
      getTreeOrBuilderList() {
    return tree_;
  }
  /**
   * <pre>
   * Trees matching the list request filters.
   * </pre>
   *
   * <code>repeated .trillian.Tree tree = 1;</code>
   */
  public int getTreeCount() {
    return tree_.size();
  }
  /**
   * <pre>
   * Trees matching the list request filters.
   * </pre>
   *
   * <code>repeated .trillian.Tree tree = 1;</code>
   */
  public com.google.trillian.proto.Tree getTree(int index) {
    return tree_.get(index);
  }
  /**
   * <pre>
   * Trees matching the list request filters.
   * </pre>
   *
   * <code>repeated .trillian.Tree tree = 1;</code>
   */
  public com.google.trillian.proto.TreeOrBuilder getTreeOrBuilder(
      int index) {
    return tree_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tree_.size(); i++) {
      output.writeMessage(1, tree_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tree_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tree_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.trillian.proto.ListTreesResponse)) {
      return super.equals(obj);
    }
    com.google.trillian.proto.ListTreesResponse other = (com.google.trillian.proto.ListTreesResponse) obj;

    boolean result = true;
    result = result && getTreeList()
        .equals(other.getTreeList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTreeCount() > 0) {
      hash = (37 * hash) + TREE_FIELD_NUMBER;
      hash = (53 * hash) + getTreeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.ListTreesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.ListTreesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.ListTreesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.ListTreesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListTrees response.
   * No pagination is provided, all trees the requester has access to are
   * returned.
   * </pre>
   *
   * Protobuf type {@code trillian.ListTreesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.ListTreesResponse)
      com.google.trillian.proto.ListTreesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.trillian.proto.TrillianAdminApiProto.internal_static_trillian_ListTreesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.trillian.proto.TrillianAdminApiProto.internal_static_trillian_ListTreesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.trillian.proto.ListTreesResponse.class, com.google.trillian.proto.ListTreesResponse.Builder.class);
    }

    // Construct using com.google.trillian.proto.ListTreesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTreeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (treeBuilder_ == null) {
        tree_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        treeBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.trillian.proto.TrillianAdminApiProto.internal_static_trillian_ListTreesResponse_descriptor;
    }

    public com.google.trillian.proto.ListTreesResponse getDefaultInstanceForType() {
      return com.google.trillian.proto.ListTreesResponse.getDefaultInstance();
    }

    public com.google.trillian.proto.ListTreesResponse build() {
      com.google.trillian.proto.ListTreesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.trillian.proto.ListTreesResponse buildPartial() {
      com.google.trillian.proto.ListTreesResponse result = new com.google.trillian.proto.ListTreesResponse(this);
      int from_bitField0_ = bitField0_;
      if (treeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tree_ = java.util.Collections.unmodifiableList(tree_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tree_ = tree_;
      } else {
        result.tree_ = treeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.trillian.proto.ListTreesResponse) {
        return mergeFrom((com.google.trillian.proto.ListTreesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.trillian.proto.ListTreesResponse other) {
      if (other == com.google.trillian.proto.ListTreesResponse.getDefaultInstance()) return this;
      if (treeBuilder_ == null) {
        if (!other.tree_.isEmpty()) {
          if (tree_.isEmpty()) {
            tree_ = other.tree_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTreeIsMutable();
            tree_.addAll(other.tree_);
          }
          onChanged();
        }
      } else {
        if (!other.tree_.isEmpty()) {
          if (treeBuilder_.isEmpty()) {
            treeBuilder_.dispose();
            treeBuilder_ = null;
            tree_ = other.tree_;
            bitField0_ = (bitField0_ & ~0x00000001);
            treeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTreeFieldBuilder() : null;
          } else {
            treeBuilder_.addAllMessages(other.tree_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.trillian.proto.ListTreesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.trillian.proto.ListTreesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.trillian.proto.Tree> tree_ =
      java.util.Collections.emptyList();
    private void ensureTreeIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tree_ = new java.util.ArrayList<com.google.trillian.proto.Tree>(tree_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.trillian.proto.Tree, com.google.trillian.proto.Tree.Builder, com.google.trillian.proto.TreeOrBuilder> treeBuilder_;

    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public java.util.List<com.google.trillian.proto.Tree> getTreeList() {
      if (treeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tree_);
      } else {
        return treeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public int getTreeCount() {
      if (treeBuilder_ == null) {
        return tree_.size();
      } else {
        return treeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public com.google.trillian.proto.Tree getTree(int index) {
      if (treeBuilder_ == null) {
        return tree_.get(index);
      } else {
        return treeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder setTree(
        int index, com.google.trillian.proto.Tree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.set(index, value);
        onChanged();
      } else {
        treeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder setTree(
        int index, com.google.trillian.proto.Tree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.set(index, builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder addTree(com.google.trillian.proto.Tree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.add(value);
        onChanged();
      } else {
        treeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder addTree(
        int index, com.google.trillian.proto.Tree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.add(index, value);
        onChanged();
      } else {
        treeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder addTree(
        com.google.trillian.proto.Tree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.add(builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder addTree(
        int index, com.google.trillian.proto.Tree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.add(index, builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder addAllTree(
        java.lang.Iterable<? extends com.google.trillian.proto.Tree> values) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tree_);
        onChanged();
      } else {
        treeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder clearTree() {
      if (treeBuilder_ == null) {
        tree_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        treeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public Builder removeTree(int index) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.remove(index);
        onChanged();
      } else {
        treeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public com.google.trillian.proto.Tree.Builder getTreeBuilder(
        int index) {
      return getTreeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public com.google.trillian.proto.TreeOrBuilder getTreeOrBuilder(
        int index) {
      if (treeBuilder_ == null) {
        return tree_.get(index);  } else {
        return treeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public java.util.List<? extends com.google.trillian.proto.TreeOrBuilder> 
         getTreeOrBuilderList() {
      if (treeBuilder_ != null) {
        return treeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tree_);
      }
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public com.google.trillian.proto.Tree.Builder addTreeBuilder() {
      return getTreeFieldBuilder().addBuilder(
          com.google.trillian.proto.Tree.getDefaultInstance());
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public com.google.trillian.proto.Tree.Builder addTreeBuilder(
        int index) {
      return getTreeFieldBuilder().addBuilder(
          index, com.google.trillian.proto.Tree.getDefaultInstance());
    }
    /**
     * <pre>
     * Trees matching the list request filters.
     * </pre>
     *
     * <code>repeated .trillian.Tree tree = 1;</code>
     */
    public java.util.List<com.google.trillian.proto.Tree.Builder> 
         getTreeBuilderList() {
      return getTreeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.trillian.proto.Tree, com.google.trillian.proto.Tree.Builder, com.google.trillian.proto.TreeOrBuilder> 
        getTreeFieldBuilder() {
      if (treeBuilder_ == null) {
        treeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.trillian.proto.Tree, com.google.trillian.proto.Tree.Builder, com.google.trillian.proto.TreeOrBuilder>(
                tree_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        tree_ = null;
      }
      return treeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trillian.ListTreesResponse)
  }

  // @@protoc_insertion_point(class_scope:trillian.ListTreesResponse)
  private static final com.google.trillian.proto.ListTreesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.trillian.proto.ListTreesResponse();
  }

  public static com.google.trillian.proto.ListTreesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTreesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListTreesResponse>() {
    public ListTreesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListTreesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListTreesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTreesResponse> getParserForType() {
    return PARSER;
  }

  public com.google.trillian.proto.ListTreesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

