// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian.proto

package com.google.trillian.proto;

/**
 * <pre>
 * LogRootFormat specifies the fields that are covered by the
 * SignedLogRoot signature, as well as their ordering and formats.
 * </pre>
 *
 * Protobuf enum {@code trillian.LogRootFormat}
 */
public enum LogRootFormat
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LOG_ROOT_FORMAT_UNKNOWN = 0;</code>
   */
  LOG_ROOT_FORMAT_UNKNOWN(0),
  /**
   * <code>LOG_ROOT_FORMAT_V1 = 1;</code>
   */
  LOG_ROOT_FORMAT_V1(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LOG_ROOT_FORMAT_UNKNOWN = 0;</code>
   */
  public static final int LOG_ROOT_FORMAT_UNKNOWN_VALUE = 0;
  /**
   * <code>LOG_ROOT_FORMAT_V1 = 1;</code>
   */
  public static final int LOG_ROOT_FORMAT_V1_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LogRootFormat valueOf(int value) {
    return forNumber(value);
  }

  public static LogRootFormat forNumber(int value) {
    switch (value) {
      case 0: return LOG_ROOT_FORMAT_UNKNOWN;
      case 1: return LOG_ROOT_FORMAT_V1;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LogRootFormat>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LogRootFormat> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LogRootFormat>() {
          public LogRootFormat findValueByNumber(int number) {
            return LogRootFormat.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final LogRootFormat[] VALUES = values();

  public static LogRootFormat valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LogRootFormat(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:trillian.LogRootFormat)
}

