// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package com.google.trillian.proto;

/**
 * Protobuf type {@code trillian.MapLeafInclusion}
 */
public  final class MapLeafInclusion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trillian.MapLeafInclusion)
    MapLeafInclusionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MapLeafInclusion.newBuilder() to construct.
  private MapLeafInclusion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MapLeafInclusion() {
    inclusion_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MapLeafInclusion(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.trillian.proto.MapLeaf.Builder subBuilder = null;
            if (leaf_ != null) {
              subBuilder = leaf_.toBuilder();
            }
            leaf_ = input.readMessage(com.google.trillian.proto.MapLeaf.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(leaf_);
              leaf_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              inclusion_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000002;
            }
            inclusion_.add(input.readBytes());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        inclusion_ = java.util.Collections.unmodifiableList(inclusion_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianMapApiProto.internal_static_trillian_MapLeafInclusion_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.trillian.proto.TrillianMapApiProto.internal_static_trillian_MapLeafInclusion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.trillian.proto.MapLeafInclusion.class, com.google.trillian.proto.MapLeafInclusion.Builder.class);
  }

  private int bitField0_;
  public static final int LEAF_FIELD_NUMBER = 1;
  private com.google.trillian.proto.MapLeaf leaf_;
  /**
   * <code>.trillian.MapLeaf leaf = 1;</code>
   */
  public boolean hasLeaf() {
    return leaf_ != null;
  }
  /**
   * <code>.trillian.MapLeaf leaf = 1;</code>
   */
  public com.google.trillian.proto.MapLeaf getLeaf() {
    return leaf_ == null ? com.google.trillian.proto.MapLeaf.getDefaultInstance() : leaf_;
  }
  /**
   * <code>.trillian.MapLeaf leaf = 1;</code>
   */
  public com.google.trillian.proto.MapLeafOrBuilder getLeafOrBuilder() {
    return getLeaf();
  }

  public static final int INCLUSION_FIELD_NUMBER = 2;
  private java.util.List<com.google.protobuf.ByteString> inclusion_;
  /**
   * <pre>
   * inclusion holds the inclusion proof for this leaf in the map root. It
   * holds one entry for each level of the tree; combining each of these in
   * turn with the leaf's hash (according to the tree's hash strategy)
   * reproduces the root hash.  A nil entry for a particular level indicates
   * that the node in question has an empty subtree beneath it (and so its
   * associated hash value is hasher.HashEmpty(index, height) rather than
   * hasher.HashChildren(l_hash, r_hash)).
   * </pre>
   *
   * <code>repeated bytes inclusion = 2;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getInclusionList() {
    return inclusion_;
  }
  /**
   * <pre>
   * inclusion holds the inclusion proof for this leaf in the map root. It
   * holds one entry for each level of the tree; combining each of these in
   * turn with the leaf's hash (according to the tree's hash strategy)
   * reproduces the root hash.  A nil entry for a particular level indicates
   * that the node in question has an empty subtree beneath it (and so its
   * associated hash value is hasher.HashEmpty(index, height) rather than
   * hasher.HashChildren(l_hash, r_hash)).
   * </pre>
   *
   * <code>repeated bytes inclusion = 2;</code>
   */
  public int getInclusionCount() {
    return inclusion_.size();
  }
  /**
   * <pre>
   * inclusion holds the inclusion proof for this leaf in the map root. It
   * holds one entry for each level of the tree; combining each of these in
   * turn with the leaf's hash (according to the tree's hash strategy)
   * reproduces the root hash.  A nil entry for a particular level indicates
   * that the node in question has an empty subtree beneath it (and so its
   * associated hash value is hasher.HashEmpty(index, height) rather than
   * hasher.HashChildren(l_hash, r_hash)).
   * </pre>
   *
   * <code>repeated bytes inclusion = 2;</code>
   */
  public com.google.protobuf.ByteString getInclusion(int index) {
    return inclusion_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leaf_ != null) {
      output.writeMessage(1, getLeaf());
    }
    for (int i = 0; i < inclusion_.size(); i++) {
      output.writeBytes(2, inclusion_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leaf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeaf());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inclusion_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(inclusion_.get(i));
      }
      size += dataSize;
      size += 1 * getInclusionList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.trillian.proto.MapLeafInclusion)) {
      return super.equals(obj);
    }
    com.google.trillian.proto.MapLeafInclusion other = (com.google.trillian.proto.MapLeafInclusion) obj;

    boolean result = true;
    result = result && (hasLeaf() == other.hasLeaf());
    if (hasLeaf()) {
      result = result && getLeaf()
          .equals(other.getLeaf());
    }
    result = result && getInclusionList()
        .equals(other.getInclusionList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeaf()) {
      hash = (37 * hash) + LEAF_FIELD_NUMBER;
      hash = (53 * hash) + getLeaf().hashCode();
    }
    if (getInclusionCount() > 0) {
      hash = (37 * hash) + INCLUSION_FIELD_NUMBER;
      hash = (53 * hash) + getInclusionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.MapLeafInclusion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.MapLeafInclusion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trillian.MapLeafInclusion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.MapLeafInclusion)
      com.google.trillian.proto.MapLeafInclusionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.trillian.proto.TrillianMapApiProto.internal_static_trillian_MapLeafInclusion_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.trillian.proto.TrillianMapApiProto.internal_static_trillian_MapLeafInclusion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.trillian.proto.MapLeafInclusion.class, com.google.trillian.proto.MapLeafInclusion.Builder.class);
    }

    // Construct using com.google.trillian.proto.MapLeafInclusion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (leafBuilder_ == null) {
        leaf_ = null;
      } else {
        leaf_ = null;
        leafBuilder_ = null;
      }
      inclusion_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.trillian.proto.TrillianMapApiProto.internal_static_trillian_MapLeafInclusion_descriptor;
    }

    public com.google.trillian.proto.MapLeafInclusion getDefaultInstanceForType() {
      return com.google.trillian.proto.MapLeafInclusion.getDefaultInstance();
    }

    public com.google.trillian.proto.MapLeafInclusion build() {
      com.google.trillian.proto.MapLeafInclusion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.trillian.proto.MapLeafInclusion buildPartial() {
      com.google.trillian.proto.MapLeafInclusion result = new com.google.trillian.proto.MapLeafInclusion(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (leafBuilder_ == null) {
        result.leaf_ = leaf_;
      } else {
        result.leaf_ = leafBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        inclusion_ = java.util.Collections.unmodifiableList(inclusion_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.inclusion_ = inclusion_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.trillian.proto.MapLeafInclusion) {
        return mergeFrom((com.google.trillian.proto.MapLeafInclusion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.trillian.proto.MapLeafInclusion other) {
      if (other == com.google.trillian.proto.MapLeafInclusion.getDefaultInstance()) return this;
      if (other.hasLeaf()) {
        mergeLeaf(other.getLeaf());
      }
      if (!other.inclusion_.isEmpty()) {
        if (inclusion_.isEmpty()) {
          inclusion_ = other.inclusion_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureInclusionIsMutable();
          inclusion_.addAll(other.inclusion_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.trillian.proto.MapLeafInclusion parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.trillian.proto.MapLeafInclusion) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.trillian.proto.MapLeaf leaf_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.MapLeaf, com.google.trillian.proto.MapLeaf.Builder, com.google.trillian.proto.MapLeafOrBuilder> leafBuilder_;
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public boolean hasLeaf() {
      return leafBuilder_ != null || leaf_ != null;
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public com.google.trillian.proto.MapLeaf getLeaf() {
      if (leafBuilder_ == null) {
        return leaf_ == null ? com.google.trillian.proto.MapLeaf.getDefaultInstance() : leaf_;
      } else {
        return leafBuilder_.getMessage();
      }
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public Builder setLeaf(com.google.trillian.proto.MapLeaf value) {
      if (leafBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leaf_ = value;
        onChanged();
      } else {
        leafBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public Builder setLeaf(
        com.google.trillian.proto.MapLeaf.Builder builderForValue) {
      if (leafBuilder_ == null) {
        leaf_ = builderForValue.build();
        onChanged();
      } else {
        leafBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public Builder mergeLeaf(com.google.trillian.proto.MapLeaf value) {
      if (leafBuilder_ == null) {
        if (leaf_ != null) {
          leaf_ =
            com.google.trillian.proto.MapLeaf.newBuilder(leaf_).mergeFrom(value).buildPartial();
        } else {
          leaf_ = value;
        }
        onChanged();
      } else {
        leafBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public Builder clearLeaf() {
      if (leafBuilder_ == null) {
        leaf_ = null;
        onChanged();
      } else {
        leaf_ = null;
        leafBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public com.google.trillian.proto.MapLeaf.Builder getLeafBuilder() {
      
      onChanged();
      return getLeafFieldBuilder().getBuilder();
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    public com.google.trillian.proto.MapLeafOrBuilder getLeafOrBuilder() {
      if (leafBuilder_ != null) {
        return leafBuilder_.getMessageOrBuilder();
      } else {
        return leaf_ == null ?
            com.google.trillian.proto.MapLeaf.getDefaultInstance() : leaf_;
      }
    }
    /**
     * <code>.trillian.MapLeaf leaf = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.MapLeaf, com.google.trillian.proto.MapLeaf.Builder, com.google.trillian.proto.MapLeafOrBuilder> 
        getLeafFieldBuilder() {
      if (leafBuilder_ == null) {
        leafBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.trillian.proto.MapLeaf, com.google.trillian.proto.MapLeaf.Builder, com.google.trillian.proto.MapLeafOrBuilder>(
                getLeaf(),
                getParentForChildren(),
                isClean());
        leaf_ = null;
      }
      return leafBuilder_;
    }

    private java.util.List<com.google.protobuf.ByteString> inclusion_ = java.util.Collections.emptyList();
    private void ensureInclusionIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        inclusion_ = new java.util.ArrayList<com.google.protobuf.ByteString>(inclusion_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getInclusionList() {
      return java.util.Collections.unmodifiableList(inclusion_);
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public int getInclusionCount() {
      return inclusion_.size();
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public com.google.protobuf.ByteString getInclusion(int index) {
      return inclusion_.get(index);
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public Builder setInclusion(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInclusionIsMutable();
      inclusion_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public Builder addInclusion(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInclusionIsMutable();
      inclusion_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public Builder addAllInclusion(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureInclusionIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inclusion_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * inclusion holds the inclusion proof for this leaf in the map root. It
     * holds one entry for each level of the tree; combining each of these in
     * turn with the leaf's hash (according to the tree's hash strategy)
     * reproduces the root hash.  A nil entry for a particular level indicates
     * that the node in question has an empty subtree beneath it (and so its
     * associated hash value is hasher.HashEmpty(index, height) rather than
     * hasher.HashChildren(l_hash, r_hash)).
     * </pre>
     *
     * <code>repeated bytes inclusion = 2;</code>
     */
    public Builder clearInclusion() {
      inclusion_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trillian.MapLeafInclusion)
  }

  // @@protoc_insertion_point(class_scope:trillian.MapLeafInclusion)
  private static final com.google.trillian.proto.MapLeafInclusion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.trillian.proto.MapLeafInclusion();
  }

  public static com.google.trillian.proto.MapLeafInclusion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MapLeafInclusion>
      PARSER = new com.google.protobuf.AbstractParser<MapLeafInclusion>() {
    public MapLeafInclusion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MapLeafInclusion(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MapLeafInclusion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MapLeafInclusion> getParserForType() {
    return PARSER;
  }

  public com.google.trillian.proto.MapLeafInclusion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

