// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package com.google.trillian.proto;

public interface MapLeavesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.MapLeaves)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  java.util.List<com.google.trillian.proto.MapLeaf> 
      getLeavesList();
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  com.google.trillian.proto.MapLeaf getLeaves(int index);
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  int getLeavesCount();
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  java.util.List<? extends com.google.trillian.proto.MapLeafOrBuilder> 
      getLeavesOrBuilderList();
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  com.google.trillian.proto.MapLeafOrBuilder getLeavesOrBuilder(
      int index);
}
