// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_log_api.proto

package com.google.trillian.proto;

/**
 * Protobuf type {@code trillian.QueueLeafResponse}
 */
public  final class QueueLeafResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trillian.QueueLeafResponse)
    QueueLeafResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueueLeafResponse.newBuilder() to construct.
  private QueueLeafResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueueLeafResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueueLeafResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            com.google.trillian.proto.QueuedLogLeaf.Builder subBuilder = null;
            if (queuedLeaf_ != null) {
              subBuilder = queuedLeaf_.toBuilder();
            }
            queuedLeaf_ = input.readMessage(com.google.trillian.proto.QueuedLogLeaf.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(queuedLeaf_);
              queuedLeaf_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_QueueLeafResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_QueueLeafResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.trillian.proto.QueueLeafResponse.class, com.google.trillian.proto.QueueLeafResponse.Builder.class);
  }

  public static final int QUEUED_LEAF_FIELD_NUMBER = 2;
  private com.google.trillian.proto.QueuedLogLeaf queuedLeaf_;
  /**
   * <pre>
   * queued_leaf describes the leaf which is or will be incorporated into the
   * Log.  If the submitted leaf was already present in the Log (as indicated by
   * its leaf identity hash), then the returned leaf will be the pre-existing
   * leaf entry rather than the submitted leaf.
   * </pre>
   *
   * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
   */
  public boolean hasQueuedLeaf() {
    return queuedLeaf_ != null;
  }
  /**
   * <pre>
   * queued_leaf describes the leaf which is or will be incorporated into the
   * Log.  If the submitted leaf was already present in the Log (as indicated by
   * its leaf identity hash), then the returned leaf will be the pre-existing
   * leaf entry rather than the submitted leaf.
   * </pre>
   *
   * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
   */
  public com.google.trillian.proto.QueuedLogLeaf getQueuedLeaf() {
    return queuedLeaf_ == null ? com.google.trillian.proto.QueuedLogLeaf.getDefaultInstance() : queuedLeaf_;
  }
  /**
   * <pre>
   * queued_leaf describes the leaf which is or will be incorporated into the
   * Log.  If the submitted leaf was already present in the Log (as indicated by
   * its leaf identity hash), then the returned leaf will be the pre-existing
   * leaf entry rather than the submitted leaf.
   * </pre>
   *
   * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
   */
  public com.google.trillian.proto.QueuedLogLeafOrBuilder getQueuedLeafOrBuilder() {
    return getQueuedLeaf();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (queuedLeaf_ != null) {
      output.writeMessage(2, getQueuedLeaf());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (queuedLeaf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getQueuedLeaf());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.trillian.proto.QueueLeafResponse)) {
      return super.equals(obj);
    }
    com.google.trillian.proto.QueueLeafResponse other = (com.google.trillian.proto.QueueLeafResponse) obj;

    boolean result = true;
    result = result && (hasQueuedLeaf() == other.hasQueuedLeaf());
    if (hasQueuedLeaf()) {
      result = result && getQueuedLeaf()
          .equals(other.getQueuedLeaf());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasQueuedLeaf()) {
      hash = (37 * hash) + QUEUED_LEAF_FIELD_NUMBER;
      hash = (53 * hash) + getQueuedLeaf().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.trillian.proto.QueueLeafResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.QueueLeafResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trillian.QueueLeafResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.QueueLeafResponse)
      com.google.trillian.proto.QueueLeafResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_QueueLeafResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_QueueLeafResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.trillian.proto.QueueLeafResponse.class, com.google.trillian.proto.QueueLeafResponse.Builder.class);
    }

    // Construct using com.google.trillian.proto.QueueLeafResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (queuedLeafBuilder_ == null) {
        queuedLeaf_ = null;
      } else {
        queuedLeaf_ = null;
        queuedLeafBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.trillian.proto.TrillianLogApiProto.internal_static_trillian_QueueLeafResponse_descriptor;
    }

    public com.google.trillian.proto.QueueLeafResponse getDefaultInstanceForType() {
      return com.google.trillian.proto.QueueLeafResponse.getDefaultInstance();
    }

    public com.google.trillian.proto.QueueLeafResponse build() {
      com.google.trillian.proto.QueueLeafResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.trillian.proto.QueueLeafResponse buildPartial() {
      com.google.trillian.proto.QueueLeafResponse result = new com.google.trillian.proto.QueueLeafResponse(this);
      if (queuedLeafBuilder_ == null) {
        result.queuedLeaf_ = queuedLeaf_;
      } else {
        result.queuedLeaf_ = queuedLeafBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.trillian.proto.QueueLeafResponse) {
        return mergeFrom((com.google.trillian.proto.QueueLeafResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.trillian.proto.QueueLeafResponse other) {
      if (other == com.google.trillian.proto.QueueLeafResponse.getDefaultInstance()) return this;
      if (other.hasQueuedLeaf()) {
        mergeQueuedLeaf(other.getQueuedLeaf());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.trillian.proto.QueueLeafResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.trillian.proto.QueueLeafResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.trillian.proto.QueuedLogLeaf queuedLeaf_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.QueuedLogLeaf, com.google.trillian.proto.QueuedLogLeaf.Builder, com.google.trillian.proto.QueuedLogLeafOrBuilder> queuedLeafBuilder_;
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public boolean hasQueuedLeaf() {
      return queuedLeafBuilder_ != null || queuedLeaf_ != null;
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public com.google.trillian.proto.QueuedLogLeaf getQueuedLeaf() {
      if (queuedLeafBuilder_ == null) {
        return queuedLeaf_ == null ? com.google.trillian.proto.QueuedLogLeaf.getDefaultInstance() : queuedLeaf_;
      } else {
        return queuedLeafBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public Builder setQueuedLeaf(com.google.trillian.proto.QueuedLogLeaf value) {
      if (queuedLeafBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        queuedLeaf_ = value;
        onChanged();
      } else {
        queuedLeafBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public Builder setQueuedLeaf(
        com.google.trillian.proto.QueuedLogLeaf.Builder builderForValue) {
      if (queuedLeafBuilder_ == null) {
        queuedLeaf_ = builderForValue.build();
        onChanged();
      } else {
        queuedLeafBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public Builder mergeQueuedLeaf(com.google.trillian.proto.QueuedLogLeaf value) {
      if (queuedLeafBuilder_ == null) {
        if (queuedLeaf_ != null) {
          queuedLeaf_ =
            com.google.trillian.proto.QueuedLogLeaf.newBuilder(queuedLeaf_).mergeFrom(value).buildPartial();
        } else {
          queuedLeaf_ = value;
        }
        onChanged();
      } else {
        queuedLeafBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public Builder clearQueuedLeaf() {
      if (queuedLeafBuilder_ == null) {
        queuedLeaf_ = null;
        onChanged();
      } else {
        queuedLeaf_ = null;
        queuedLeafBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public com.google.trillian.proto.QueuedLogLeaf.Builder getQueuedLeafBuilder() {
      
      onChanged();
      return getQueuedLeafFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    public com.google.trillian.proto.QueuedLogLeafOrBuilder getQueuedLeafOrBuilder() {
      if (queuedLeafBuilder_ != null) {
        return queuedLeafBuilder_.getMessageOrBuilder();
      } else {
        return queuedLeaf_ == null ?
            com.google.trillian.proto.QueuedLogLeaf.getDefaultInstance() : queuedLeaf_;
      }
    }
    /**
     * <pre>
     * queued_leaf describes the leaf which is or will be incorporated into the
     * Log.  If the submitted leaf was already present in the Log (as indicated by
     * its leaf identity hash), then the returned leaf will be the pre-existing
     * leaf entry rather than the submitted leaf.
     * </pre>
     *
     * <code>.trillian.QueuedLogLeaf queued_leaf = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.trillian.proto.QueuedLogLeaf, com.google.trillian.proto.QueuedLogLeaf.Builder, com.google.trillian.proto.QueuedLogLeafOrBuilder> 
        getQueuedLeafFieldBuilder() {
      if (queuedLeafBuilder_ == null) {
        queuedLeafBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.trillian.proto.QueuedLogLeaf, com.google.trillian.proto.QueuedLogLeaf.Builder, com.google.trillian.proto.QueuedLogLeafOrBuilder>(
                getQueuedLeaf(),
                getParentForChildren(),
                isClean());
        queuedLeaf_ = null;
      }
      return queuedLeafBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trillian.QueueLeafResponse)
  }

  // @@protoc_insertion_point(class_scope:trillian.QueueLeafResponse)
  private static final com.google.trillian.proto.QueueLeafResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.trillian.proto.QueueLeafResponse();
  }

  public static com.google.trillian.proto.QueueLeafResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueueLeafResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueueLeafResponse>() {
    public QueueLeafResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueueLeafResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueueLeafResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueueLeafResponse> getParserForType() {
    return PARSER;
  }

  public com.google.trillian.proto.QueueLeafResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

