// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian.proto

package com.google.trillian.proto;

/**
 * Protobuf type {@code trillian.SignedEntryTimestamp}
 */
public  final class SignedEntryTimestamp extends
    com.google.protobuf.GeneratedMessageLite<
        SignedEntryTimestamp, SignedEntryTimestamp.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.SignedEntryTimestamp)
    SignedEntryTimestampOrBuilder {
  private SignedEntryTimestamp() {
  }
  public static final int TIMESTAMP_NANOS_FIELD_NUMBER = 1;
  private long timestampNanos_;
  /**
   * <code>int64 timestamp_nanos = 1;</code>
   * @return The timestampNanos.
   */
  @java.lang.Override
  public long getTimestampNanos() {
    return timestampNanos_;
  }
  /**
   * <code>int64 timestamp_nanos = 1;</code>
   * @param value The timestampNanos to set.
   */
  private void setTimestampNanos(long value) {
    
    timestampNanos_ = value;
  }
  /**
   * <code>int64 timestamp_nanos = 1;</code>
   */
  private void clearTimestampNanos() {
    
    timestampNanos_ = 0L;
  }

  public static final int LOG_ID_FIELD_NUMBER = 2;
  private long logId_;
  /**
   * <code>int64 log_id = 2;</code>
   * @return The logId.
   */
  @java.lang.Override
  public long getLogId() {
    return logId_;
  }
  /**
   * <code>int64 log_id = 2;</code>
   * @param value The logId to set.
   */
  private void setLogId(long value) {
    
    logId_ = value;
  }
  /**
   * <code>int64 log_id = 2;</code>
   */
  private void clearLogId() {
    
    logId_ = 0L;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 3;
  private sigpb.Sigpb.DigitallySigned signature_;
  /**
   * <code>.sigpb.DigitallySigned signature = 3;</code>
   */
  @java.lang.Override
  public boolean hasSignature() {
    return signature_ != null;
  }
  /**
   * <code>.sigpb.DigitallySigned signature = 3;</code>
   */
  @java.lang.Override
  public sigpb.Sigpb.DigitallySigned getSignature() {
    return signature_ == null ? sigpb.Sigpb.DigitallySigned.getDefaultInstance() : signature_;
  }
  /**
   * <code>.sigpb.DigitallySigned signature = 3;</code>
   */
  private void setSignature(sigpb.Sigpb.DigitallySigned value) {
    value.getClass();
  signature_ = value;
    
    }
  /**
   * <code>.sigpb.DigitallySigned signature = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSignature(sigpb.Sigpb.DigitallySigned value) {
    value.getClass();
  if (signature_ != null &&
        signature_ != sigpb.Sigpb.DigitallySigned.getDefaultInstance()) {
      signature_ =
        sigpb.Sigpb.DigitallySigned.newBuilder(signature_).mergeFrom(value).buildPartial();
    } else {
      signature_ = value;
    }
    
  }
  /**
   * <code>.sigpb.DigitallySigned signature = 3;</code>
   */
  private void clearSignature() {  signature_ = null;
    
  }

  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.trillian.proto.SignedEntryTimestamp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.trillian.proto.SignedEntryTimestamp prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code trillian.SignedEntryTimestamp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.trillian.proto.SignedEntryTimestamp, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.SignedEntryTimestamp)
      com.google.trillian.proto.SignedEntryTimestampOrBuilder {
    // Construct using com.google.trillian.proto.SignedEntryTimestamp.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 timestamp_nanos = 1;</code>
     * @return The timestampNanos.
     */
    @java.lang.Override
    public long getTimestampNanos() {
      return instance.getTimestampNanos();
    }
    /**
     * <code>int64 timestamp_nanos = 1;</code>
     * @param value The timestampNanos to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampNanos(long value) {
      copyOnWrite();
      instance.setTimestampNanos(value);
      return this;
    }
    /**
     * <code>int64 timestamp_nanos = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampNanos() {
      copyOnWrite();
      instance.clearTimestampNanos();
      return this;
    }

    /**
     * <code>int64 log_id = 2;</code>
     * @return The logId.
     */
    @java.lang.Override
    public long getLogId() {
      return instance.getLogId();
    }
    /**
     * <code>int64 log_id = 2;</code>
     * @param value The logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogId(long value) {
      copyOnWrite();
      instance.setLogId(value);
      return this;
    }
    /**
     * <code>int64 log_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogId() {
      copyOnWrite();
      instance.clearLogId();
      return this;
    }

    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    @java.lang.Override
    public boolean hasSignature() {
      return instance.hasSignature();
    }
    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    @java.lang.Override
    public sigpb.Sigpb.DigitallySigned getSignature() {
      return instance.getSignature();
    }
    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    public Builder setSignature(sigpb.Sigpb.DigitallySigned value) {
      copyOnWrite();
      instance.setSignature(value);
      return this;
      }
    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    public Builder setSignature(
        sigpb.Sigpb.DigitallySigned.Builder builderForValue) {
      copyOnWrite();
      instance.setSignature(builderForValue.build());
      return this;
    }
    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    public Builder mergeSignature(sigpb.Sigpb.DigitallySigned value) {
      copyOnWrite();
      instance.mergeSignature(value);
      return this;
    }
    /**
     * <code>.sigpb.DigitallySigned signature = 3;</code>
     */
    public Builder clearSignature() {  copyOnWrite();
      instance.clearSignature();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.SignedEntryTimestamp)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.trillian.proto.SignedEntryTimestamp();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "timestampNanos_",
            "logId_",
            "signature_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
              "\u0003\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.trillian.proto.SignedEntryTimestamp> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.trillian.proto.SignedEntryTimestamp.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.trillian.proto.SignedEntryTimestamp>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.SignedEntryTimestamp)
  private static final com.google.trillian.proto.SignedEntryTimestamp DEFAULT_INSTANCE;
  static {
    SignedEntryTimestamp defaultInstance = new SignedEntryTimestamp();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SignedEntryTimestamp.class, defaultInstance);
  }

  public static com.google.trillian.proto.SignedEntryTimestamp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SignedEntryTimestamp> PARSER;

  public static com.google.protobuf.Parser<SignedEntryTimestamp> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

