// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_admin_api.proto

package google.trillian.proto;

/**
 * <pre>
 * DeleteTree request.
 * </pre>
 *
 * Protobuf type {@code trillian.DeleteTreeRequest}
 */
public  final class DeleteTreeRequest extends
    com.google.protobuf.GeneratedMessageLite<
        DeleteTreeRequest, DeleteTreeRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.DeleteTreeRequest)
    DeleteTreeRequestOrBuilder {
  private DeleteTreeRequest() {
  }
  public static final int TREE_ID_FIELD_NUMBER = 1;
  private long treeId_;
  /**
   * <pre>
   * ID of the tree to delete.
   * </pre>
   *
   * <code>int64 tree_id = 1;</code>
   * @return The treeId.
   */
  @java.lang.Override
  public long getTreeId() {
    return treeId_;
  }
  /**
   * <pre>
   * ID of the tree to delete.
   * </pre>
   *
   * <code>int64 tree_id = 1;</code>
   * @param value The treeId to set.
   */
  private void setTreeId(long value) {
    
    treeId_ = value;
  }
  /**
   * <pre>
   * ID of the tree to delete.
   * </pre>
   *
   * <code>int64 tree_id = 1;</code>
   */
  private void clearTreeId() {
    
    treeId_ = 0L;
  }

  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.DeleteTreeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.DeleteTreeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.DeleteTreeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.DeleteTreeRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * DeleteTree request.
   * </pre>
   *
   * Protobuf type {@code trillian.DeleteTreeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.DeleteTreeRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.DeleteTreeRequest)
      google.trillian.proto.DeleteTreeRequestOrBuilder {
    // Construct using google.trillian.proto.DeleteTreeRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * ID of the tree to delete.
     * </pre>
     *
     * <code>int64 tree_id = 1;</code>
     * @return The treeId.
     */
    @java.lang.Override
    public long getTreeId() {
      return instance.getTreeId();
    }
    /**
     * <pre>
     * ID of the tree to delete.
     * </pre>
     *
     * <code>int64 tree_id = 1;</code>
     * @param value The treeId to set.
     * @return This builder for chaining.
     */
    public Builder setTreeId(long value) {
      copyOnWrite();
      instance.setTreeId(value);
      return this;
    }
    /**
     * <pre>
     * ID of the tree to delete.
     * </pre>
     *
     * <code>int64 tree_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTreeId() {
      copyOnWrite();
      instance.clearTreeId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.DeleteTreeRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.DeleteTreeRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "treeId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.DeleteTreeRequest> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.DeleteTreeRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.DeleteTreeRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.DeleteTreeRequest)
  private static final google.trillian.proto.DeleteTreeRequest DEFAULT_INSTANCE;
  static {
    DeleteTreeRequest defaultInstance = new DeleteTreeRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeleteTreeRequest.class, defaultInstance);
  }

  public static google.trillian.proto.DeleteTreeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeleteTreeRequest> PARSER;

  public static com.google.protobuf.Parser<DeleteTreeRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

