// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

/**
 * Protobuf type {@code trillian.GetMapLeafRequest}
 */
public  final class GetMapLeafRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetMapLeafRequest, GetMapLeafRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.GetMapLeafRequest)
    GetMapLeafRequestOrBuilder {
  private GetMapLeafRequest() {
    index_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int MAP_ID_FIELD_NUMBER = 1;
  private long mapId_;
  /**
   * <code>int64 map_id = 1;</code>
   * @return The mapId.
   */
  @java.lang.Override
  public long getMapId() {
    return mapId_;
  }
  /**
   * <code>int64 map_id = 1;</code>
   * @param value The mapId to set.
   */
  private void setMapId(long value) {
    
    mapId_ = value;
  }
  /**
   * <code>int64 map_id = 1;</code>
   */
  private void clearMapId() {
    
    mapId_ = 0L;
  }

  public static final int INDEX_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString index_;
  /**
   * <code>bytes index = 2;</code>
   * @return The index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIndex() {
    return index_;
  }
  /**
   * <code>bytes index = 2;</code>
   * @param value The index to set.
   */
  private void setIndex(com.google.protobuf.ByteString value) {
    value.getClass();
  
    index_ = value;
  }
  /**
   * <code>bytes index = 2;</code>
   */
  private void clearIndex() {
    
    index_ = getDefaultInstance().getIndex();
  }

  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeafRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeafRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeafRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.GetMapLeafRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code trillian.GetMapLeafRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.GetMapLeafRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.GetMapLeafRequest)
      google.trillian.proto.GetMapLeafRequestOrBuilder {
    // Construct using google.trillian.proto.GetMapLeafRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 map_id = 1;</code>
     * @return The mapId.
     */
    @java.lang.Override
    public long getMapId() {
      return instance.getMapId();
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @param value The mapId to set.
     * @return This builder for chaining.
     */
    public Builder setMapId(long value) {
      copyOnWrite();
      instance.setMapId(value);
      return this;
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapId() {
      copyOnWrite();
      instance.clearMapId();
      return this;
    }

    /**
     * <code>bytes index = 2;</code>
     * @return The index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIndex() {
      return instance.getIndex();
    }
    /**
     * <code>bytes index = 2;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIndex(value);
      return this;
    }
    /**
     * <code>bytes index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      copyOnWrite();
      instance.clearIndex();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.GetMapLeafRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.GetMapLeafRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mapId_",
            "index_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\n" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.GetMapLeafRequest> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.GetMapLeafRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.GetMapLeafRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.GetMapLeafRequest)
  private static final google.trillian.proto.GetMapLeafRequest DEFAULT_INSTANCE;
  static {
    GetMapLeafRequest defaultInstance = new GetMapLeafRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetMapLeafRequest.class, defaultInstance);
  }

  public static google.trillian.proto.GetMapLeafRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetMapLeafRequest> PARSER;

  public static com.google.protobuf.Parser<GetMapLeafRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

