// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

public interface GetMapLeavesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetMapLeavesResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .trillian.MapLeafInclusion map_leaf_inclusion = 2;</code>
   */
  java.util.List<google.trillian.proto.MapLeafInclusion> 
      getMapLeafInclusionList();
  /**
   * <code>repeated .trillian.MapLeafInclusion map_leaf_inclusion = 2;</code>
   */
  google.trillian.proto.MapLeafInclusion getMapLeafInclusion(int index);
  /**
   * <code>repeated .trillian.MapLeafInclusion map_leaf_inclusion = 2;</code>
   */
  int getMapLeafInclusionCount();

  /**
   * <code>.trillian.SignedMapRoot map_root = 3;</code>
   * @return Whether the mapRoot field is set.
   */
  boolean hasMapRoot();
  /**
   * <code>.trillian.SignedMapRoot map_root = 3;</code>
   * @return The mapRoot.
   */
  google.trillian.proto.SignedMapRoot getMapRoot();
}
