// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

public interface GetMapLeafResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetMapLeafResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.trillian.MapLeafInclusion map_leaf_inclusion = 1;</code>
   * @return Whether the mapLeafInclusion field is set.
   */
  boolean hasMapLeafInclusion();
  /**
   * <code>.trillian.MapLeafInclusion map_leaf_inclusion = 1;</code>
   * @return The mapLeafInclusion.
   */
  google.trillian.proto.MapLeafInclusion getMapLeafInclusion();

  /**
   * <code>.trillian.SignedMapRoot map_root = 2;</code>
   * @return Whether the mapRoot field is set.
   */
  boolean hasMapRoot();
  /**
   * <code>.trillian.SignedMapRoot map_root = 2;</code>
   * @return The mapRoot.
   */
  google.trillian.proto.SignedMapRoot getMapRoot();
}
