// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

/**
 * <pre>
 * This message replaces the current implementation of GetMapLeavesRequest
 * with the difference that revision must be &gt;=0.
 * </pre>
 *
 * Protobuf type {@code trillian.GetMapLeavesByRevisionRequest}
 */
public  final class GetMapLeavesByRevisionRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetMapLeavesByRevisionRequest, GetMapLeavesByRevisionRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.GetMapLeavesByRevisionRequest)
    GetMapLeavesByRevisionRequestOrBuilder {
  private GetMapLeavesByRevisionRequest() {
    index_ = emptyProtobufList();
  }
  public static final int MAP_ID_FIELD_NUMBER = 1;
  private long mapId_;
  /**
   * <code>int64 map_id = 1;</code>
   * @return The mapId.
   */
  @java.lang.Override
  public long getMapId() {
    return mapId_;
  }
  /**
   * <code>int64 map_id = 1;</code>
   * @param value The mapId to set.
   */
  private void setMapId(long value) {
    
    mapId_ = value;
  }
  /**
   * <code>int64 map_id = 1;</code>
   */
  private void clearMapId() {
    
    mapId_ = 0L;
  }

  public static final int INDEX_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> index_;
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @return A list containing the index.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getIndexList() {
    return index_;
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @return The count of index.
   */
  @java.lang.Override
  public int getIndexCount() {
    return index_.size();
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @param index The index of the element to return.
   * @return The index at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIndex(int index) {
    return index_.get(index);
  }
  private void ensureIndexIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tmp = index_;
    if (!tmp.isModifiable()) {
      index_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @param index The index to set the value at.
   * @param value The index to set.
   */
  private void setIndex(
      int index, com.google.protobuf.ByteString value) {
    value.getClass();
  ensureIndexIsMutable();
    index_.set(index, value);
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @param value The index to add.
   */
  private void addIndex(com.google.protobuf.ByteString value) {
    value.getClass();
  ensureIndexIsMutable();
    index_.add(value);
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   * @param values The index to add.
   */
  private void addAllIndex(
      java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
    ensureIndexIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, index_);
  }
  /**
   * <pre>
   * index(es) to query.  It is an error to request the same index more than once.
   * </pre>
   *
   * <code>repeated bytes index = 2;</code>
   */
  private void clearIndex() {
    index_ = emptyProtobufList();
  }

  public static final int REVISION_FIELD_NUMBER = 3;
  private long revision_;
  /**
   * <pre>
   * revision &gt;= 0.
   * </pre>
   *
   * <code>int64 revision = 3;</code>
   * @return The revision.
   */
  @java.lang.Override
  public long getRevision() {
    return revision_;
  }
  /**
   * <pre>
   * revision &gt;= 0.
   * </pre>
   *
   * <code>int64 revision = 3;</code>
   * @param value The revision to set.
   */
  private void setRevision(long value) {
    
    revision_ = value;
  }
  /**
   * <pre>
   * revision &gt;= 0.
   * </pre>
   *
   * <code>int64 revision = 3;</code>
   */
  private void clearRevision() {
    
    revision_ = 0L;
  }

  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetMapLeavesByRevisionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.GetMapLeavesByRevisionRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * This message replaces the current implementation of GetMapLeavesRequest
   * with the difference that revision must be &gt;=0.
   * </pre>
   *
   * Protobuf type {@code trillian.GetMapLeavesByRevisionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.GetMapLeavesByRevisionRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.GetMapLeavesByRevisionRequest)
      google.trillian.proto.GetMapLeavesByRevisionRequestOrBuilder {
    // Construct using google.trillian.proto.GetMapLeavesByRevisionRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 map_id = 1;</code>
     * @return The mapId.
     */
    @java.lang.Override
    public long getMapId() {
      return instance.getMapId();
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @param value The mapId to set.
     * @return This builder for chaining.
     */
    public Builder setMapId(long value) {
      copyOnWrite();
      instance.setMapId(value);
      return this;
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapId() {
      copyOnWrite();
      instance.clearMapId();
      return this;
    }

    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @return A list containing the index.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getIndexList() {
      return java.util.Collections.unmodifiableList(
          instance.getIndexList());
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @return The count of index.
     */
    @java.lang.Override
    public int getIndexCount() {
      return instance.getIndexCount();
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @param index The index of the element to return.
     * @return The index at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIndex(int index) {
      return instance.getIndex(index);
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(
        int index, com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIndex(index, value);
      return this;
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @param value The index to add.
     * @return This builder for chaining.
     */
    public Builder addIndex(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addIndex(value);
      return this;
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @param values The index to add.
     * @return This builder for chaining.
     */
    public Builder addAllIndex(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      copyOnWrite();
      instance.addAllIndex(values);
      return this;
    }
    /**
     * <pre>
     * index(es) to query.  It is an error to request the same index more than once.
     * </pre>
     *
     * <code>repeated bytes index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      copyOnWrite();
      instance.clearIndex();
      return this;
    }

    /**
     * <pre>
     * revision &gt;= 0.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     * @return The revision.
     */
    @java.lang.Override
    public long getRevision() {
      return instance.getRevision();
    }
    /**
     * <pre>
     * revision &gt;= 0.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(long value) {
      copyOnWrite();
      instance.setRevision(value);
      return this;
    }
    /**
     * <pre>
     * revision &gt;= 0.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      copyOnWrite();
      instance.clearRevision();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.GetMapLeavesByRevisionRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.GetMapLeavesByRevisionRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mapId_",
            "index_",
            "revision_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0002\u0002\u001c" +
              "\u0003\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.GetMapLeavesByRevisionRequest> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.GetMapLeavesByRevisionRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.GetMapLeavesByRevisionRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.GetMapLeavesByRevisionRequest)
  private static final google.trillian.proto.GetMapLeavesByRevisionRequest DEFAULT_INSTANCE;
  static {
    GetMapLeavesByRevisionRequest defaultInstance = new GetMapLeavesByRevisionRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetMapLeavesByRevisionRequest.class, defaultInstance);
  }

  public static google.trillian.proto.GetMapLeavesByRevisionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetMapLeavesByRevisionRequest> PARSER;

  public static com.google.protobuf.Parser<GetMapLeavesByRevisionRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

