// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

public interface GetSignedMapRootResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetSignedMapRootResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.trillian.SignedMapRoot map_root = 2;</code>
   * @return Whether the mapRoot field is set.
   */
  boolean hasMapRoot();
  /**
   * <code>.trillian.SignedMapRoot map_root = 2;</code>
   * @return The mapRoot.
   */
  google.trillian.proto.SignedMapRoot getMapRoot();
}
