// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

/**
 * Protobuf type {@code trillian.GetSignedMapRootRequest}
 */
public  final class GetSignedMapRootRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetSignedMapRootRequest, GetSignedMapRootRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.GetSignedMapRootRequest)
    GetSignedMapRootRequestOrBuilder {
  private GetSignedMapRootRequest() {
  }
  public static final int MAP_ID_FIELD_NUMBER = 1;
  private long mapId_;
  /**
   * <code>int64 map_id = 1;</code>
   * @return The mapId.
   */
  @java.lang.Override
  public long getMapId() {
    return mapId_;
  }
  /**
   * <code>int64 map_id = 1;</code>
   * @param value The mapId to set.
   */
  private void setMapId(long value) {
    
    mapId_ = value;
  }
  /**
   * <code>int64 map_id = 1;</code>
   */
  private void clearMapId() {
    
    mapId_ = 0L;
  }

  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.GetSignedMapRootRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.GetSignedMapRootRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code trillian.GetSignedMapRootRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.GetSignedMapRootRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.GetSignedMapRootRequest)
      google.trillian.proto.GetSignedMapRootRequestOrBuilder {
    // Construct using google.trillian.proto.GetSignedMapRootRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 map_id = 1;</code>
     * @return The mapId.
     */
    @java.lang.Override
    public long getMapId() {
      return instance.getMapId();
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @param value The mapId to set.
     * @return This builder for chaining.
     */
    public Builder setMapId(long value) {
      copyOnWrite();
      instance.setMapId(value);
      return this;
    }
    /**
     * <code>int64 map_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapId() {
      copyOnWrite();
      instance.clearMapId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.GetSignedMapRootRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.GetSignedMapRootRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mapId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.GetSignedMapRootRequest> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.GetSignedMapRootRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.GetSignedMapRootRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.GetSignedMapRootRequest)
  private static final google.trillian.proto.GetSignedMapRootRequest DEFAULT_INSTANCE;
  static {
    GetSignedMapRootRequest defaultInstance = new GetSignedMapRootRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetSignedMapRootRequest.class, defaultInstance);
  }

  public static google.trillian.proto.GetSignedMapRootRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetSignedMapRootRequest> PARSER;

  public static com.google.protobuf.Parser<GetSignedMapRootRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

