// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

public interface GetSignedMapRootRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.GetSignedMapRootRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 map_id = 1;</code>
   * @return The mapId.
   */
  long getMapId();
}
