// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_admin_api.proto

package google.trillian.proto;

/**
 * <pre>
 * ListTrees request.
 * No filters or pagination options are provided.
 * </pre>
 *
 * Protobuf type {@code trillian.ListTreesRequest}
 */
public  final class ListTreesRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ListTreesRequest, ListTreesRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.ListTreesRequest)
    ListTreesRequestOrBuilder {
  private ListTreesRequest() {
  }
  public static final int SHOW_DELETED_FIELD_NUMBER = 1;
  private boolean showDeleted_;
  /**
   * <pre>
   * If true, deleted trees are included in the response.
   * </pre>
   *
   * <code>bool show_deleted = 1;</code>
   * @return The showDeleted.
   */
  @java.lang.Override
  public boolean getShowDeleted() {
    return showDeleted_;
  }
  /**
   * <pre>
   * If true, deleted trees are included in the response.
   * </pre>
   *
   * <code>bool show_deleted = 1;</code>
   * @param value The showDeleted to set.
   */
  private void setShowDeleted(boolean value) {
    
    showDeleted_ = value;
  }
  /**
   * <pre>
   * If true, deleted trees are included in the response.
   * </pre>
   *
   * <code>bool show_deleted = 1;</code>
   */
  private void clearShowDeleted() {
    
    showDeleted_ = false;
  }

  public static google.trillian.proto.ListTreesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.ListTreesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.ListTreesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.ListTreesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.ListTreesRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ListTrees request.
   * No filters or pagination options are provided.
   * </pre>
   *
   * Protobuf type {@code trillian.ListTreesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.ListTreesRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.ListTreesRequest)
      google.trillian.proto.ListTreesRequestOrBuilder {
    // Construct using google.trillian.proto.ListTreesRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * If true, deleted trees are included in the response.
     * </pre>
     *
     * <code>bool show_deleted = 1;</code>
     * @return The showDeleted.
     */
    @java.lang.Override
    public boolean getShowDeleted() {
      return instance.getShowDeleted();
    }
    /**
     * <pre>
     * If true, deleted trees are included in the response.
     * </pre>
     *
     * <code>bool show_deleted = 1;</code>
     * @param value The showDeleted to set.
     * @return This builder for chaining.
     */
    public Builder setShowDeleted(boolean value) {
      copyOnWrite();
      instance.setShowDeleted(value);
      return this;
    }
    /**
     * <pre>
     * If true, deleted trees are included in the response.
     * </pre>
     *
     * <code>bool show_deleted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShowDeleted() {
      copyOnWrite();
      instance.clearShowDeleted();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.ListTreesRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.ListTreesRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "showDeleted_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.ListTreesRequest> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.ListTreesRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.ListTreesRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.ListTreesRequest)
  private static final google.trillian.proto.ListTreesRequest DEFAULT_INSTANCE;
  static {
    ListTreesRequest defaultInstance = new ListTreesRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListTreesRequest.class, defaultInstance);
  }

  public static google.trillian.proto.ListTreesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListTreesRequest> PARSER;

  public static com.google.protobuf.Parser<ListTreesRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

