// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_admin_api.proto

package google.trillian.proto;

public interface ListTreesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.ListTreesRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * If true, deleted trees are included in the response.
   * </pre>
   *
   * <code>bool show_deleted = 1;</code>
   * @return The showDeleted.
   */
  boolean getShowDeleted();
}
