// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian_map_api.proto

package google.trillian.proto;

/**
 * Protobuf type {@code trillian.MapLeaves}
 */
public  final class MapLeaves extends
    com.google.protobuf.GeneratedMessageLite<
        MapLeaves, MapLeaves.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.MapLeaves)
    MapLeavesOrBuilder {
  private MapLeaves() {
    leaves_ = emptyProtobufList();
  }
  public static final int LEAVES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<google.trillian.proto.MapLeaf> leaves_;
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  @java.lang.Override
  public java.util.List<google.trillian.proto.MapLeaf> getLeavesList() {
    return leaves_;
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  public java.util.List<? extends google.trillian.proto.MapLeafOrBuilder> 
      getLeavesOrBuilderList() {
    return leaves_;
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  @java.lang.Override
  public int getLeavesCount() {
    return leaves_.size();
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  @java.lang.Override
  public google.trillian.proto.MapLeaf getLeaves(int index) {
    return leaves_.get(index);
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  public google.trillian.proto.MapLeafOrBuilder getLeavesOrBuilder(
      int index) {
    return leaves_.get(index);
  }
  private void ensureLeavesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<google.trillian.proto.MapLeaf> tmp = leaves_;
    if (!tmp.isModifiable()) {
      leaves_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void setLeaves(
      int index, google.trillian.proto.MapLeaf value) {
    value.getClass();
  ensureLeavesIsMutable();
    leaves_.set(index, value);
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void addLeaves(google.trillian.proto.MapLeaf value) {
    value.getClass();
  ensureLeavesIsMutable();
    leaves_.add(value);
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void addLeaves(
      int index, google.trillian.proto.MapLeaf value) {
    value.getClass();
  ensureLeavesIsMutable();
    leaves_.add(index, value);
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void addAllLeaves(
      java.lang.Iterable<? extends google.trillian.proto.MapLeaf> values) {
    ensureLeavesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, leaves_);
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void clearLeaves() {
    leaves_ = emptyProtobufList();
  }
  /**
   * <code>repeated .trillian.MapLeaf leaves = 1;</code>
   */
  private void removeLeaves(int index) {
    ensureLeavesIsMutable();
    leaves_.remove(index);
  }

  public static google.trillian.proto.MapLeaves parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.MapLeaves parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.MapLeaves parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.MapLeaves parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.MapLeaves parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.MapLeaves parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.MapLeaves prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code trillian.MapLeaves}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.MapLeaves, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.MapLeaves)
      google.trillian.proto.MapLeavesOrBuilder {
    // Construct using google.trillian.proto.MapLeaves.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    @java.lang.Override
    public java.util.List<google.trillian.proto.MapLeaf> getLeavesList() {
      return java.util.Collections.unmodifiableList(
          instance.getLeavesList());
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    @java.lang.Override
    public int getLeavesCount() {
      return instance.getLeavesCount();
    }/**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    @java.lang.Override
    public google.trillian.proto.MapLeaf getLeaves(int index) {
      return instance.getLeaves(index);
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder setLeaves(
        int index, google.trillian.proto.MapLeaf value) {
      copyOnWrite();
      instance.setLeaves(index, value);
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder setLeaves(
        int index, google.trillian.proto.MapLeaf.Builder builderForValue) {
      copyOnWrite();
      instance.setLeaves(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder addLeaves(google.trillian.proto.MapLeaf value) {
      copyOnWrite();
      instance.addLeaves(value);
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder addLeaves(
        int index, google.trillian.proto.MapLeaf value) {
      copyOnWrite();
      instance.addLeaves(index, value);
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder addLeaves(
        google.trillian.proto.MapLeaf.Builder builderForValue) {
      copyOnWrite();
      instance.addLeaves(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder addLeaves(
        int index, google.trillian.proto.MapLeaf.Builder builderForValue) {
      copyOnWrite();
      instance.addLeaves(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder addAllLeaves(
        java.lang.Iterable<? extends google.trillian.proto.MapLeaf> values) {
      copyOnWrite();
      instance.addAllLeaves(values);
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder clearLeaves() {
      copyOnWrite();
      instance.clearLeaves();
      return this;
    }
    /**
     * <code>repeated .trillian.MapLeaf leaves = 1;</code>
     */
    public Builder removeLeaves(int index) {
      copyOnWrite();
      instance.removeLeaves(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.MapLeaves)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.MapLeaves();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "leaves_",
            google.trillian.proto.MapLeaf.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.MapLeaves> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.MapLeaves.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.MapLeaves>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.MapLeaves)
  private static final google.trillian.proto.MapLeaves DEFAULT_INSTANCE;
  static {
    MapLeaves defaultInstance = new MapLeaves();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MapLeaves.class, defaultInstance);
  }

  public static google.trillian.proto.MapLeaves getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MapLeaves> PARSER;

  public static com.google.protobuf.Parser<MapLeaves> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

