// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian.proto

package google.trillian.proto;

/**
 * <pre>
 * Proof holds a consistency or inclusion proof for a Merkle tree, as returned
 * by the API.
 * </pre>
 *
 * Protobuf type {@code trillian.Proof}
 */
public  final class Proof extends
    com.google.protobuf.GeneratedMessageLite<
        Proof, Proof.Builder> implements
    // @@protoc_insertion_point(message_implements:trillian.Proof)
    ProofOrBuilder {
  private Proof() {
    hashes_ = emptyProtobufList();
  }
  public static final int LEAF_INDEX_FIELD_NUMBER = 1;
  private long leafIndex_;
  /**
   * <pre>
   * leaf_index indicates the requested leaf index when this message is used for
   * a leaf inclusion proof.  This field is set to zero when this message is
   * used for a consistency proof.
   * </pre>
   *
   * <code>int64 leaf_index = 1;</code>
   * @return The leafIndex.
   */
  @java.lang.Override
  public long getLeafIndex() {
    return leafIndex_;
  }
  /**
   * <pre>
   * leaf_index indicates the requested leaf index when this message is used for
   * a leaf inclusion proof.  This field is set to zero when this message is
   * used for a consistency proof.
   * </pre>
   *
   * <code>int64 leaf_index = 1;</code>
   * @param value The leafIndex to set.
   */
  private void setLeafIndex(long value) {
    
    leafIndex_ = value;
  }
  /**
   * <pre>
   * leaf_index indicates the requested leaf index when this message is used for
   * a leaf inclusion proof.  This field is set to zero when this message is
   * used for a consistency proof.
   * </pre>
   *
   * <code>int64 leaf_index = 1;</code>
   */
  private void clearLeafIndex() {
    
    leafIndex_ = 0L;
  }

  public static final int HASHES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> hashes_;
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @return A list containing the hashes.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getHashesList() {
    return hashes_;
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @return The count of hashes.
   */
  @java.lang.Override
  public int getHashesCount() {
    return hashes_.size();
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @param index The index of the element to return.
   * @return The hashes at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHashes(int index) {
    return hashes_.get(index);
  }
  private void ensureHashesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tmp = hashes_;
    if (!tmp.isModifiable()) {
      hashes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @param index The index to set the value at.
   * @param value The hashes to set.
   */
  private void setHashes(
      int index, com.google.protobuf.ByteString value) {
    value.getClass();
  ensureHashesIsMutable();
    hashes_.set(index, value);
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @param value The hashes to add.
   */
  private void addHashes(com.google.protobuf.ByteString value) {
    value.getClass();
  ensureHashesIsMutable();
    hashes_.add(value);
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   * @param values The hashes to add.
   */
  private void addAllHashes(
      java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
    ensureHashesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, hashes_);
  }
  /**
   * <code>repeated bytes hashes = 3;</code>
   */
  private void clearHashes() {
    hashes_ = emptyProtobufList();
  }

  public static google.trillian.proto.Proof parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.Proof parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.Proof parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.Proof parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.Proof parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static google.trillian.proto.Proof parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static google.trillian.proto.Proof parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.Proof parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.Proof parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.Proof parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static google.trillian.proto.Proof parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static google.trillian.proto.Proof parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(google.trillian.proto.Proof prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Proof holds a consistency or inclusion proof for a Merkle tree, as returned
   * by the API.
   * </pre>
   *
   * Protobuf type {@code trillian.Proof}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        google.trillian.proto.Proof, Builder> implements
      // @@protoc_insertion_point(builder_implements:trillian.Proof)
      google.trillian.proto.ProofOrBuilder {
    // Construct using google.trillian.proto.Proof.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * leaf_index indicates the requested leaf index when this message is used for
     * a leaf inclusion proof.  This field is set to zero when this message is
     * used for a consistency proof.
     * </pre>
     *
     * <code>int64 leaf_index = 1;</code>
     * @return The leafIndex.
     */
    @java.lang.Override
    public long getLeafIndex() {
      return instance.getLeafIndex();
    }
    /**
     * <pre>
     * leaf_index indicates the requested leaf index when this message is used for
     * a leaf inclusion proof.  This field is set to zero when this message is
     * used for a consistency proof.
     * </pre>
     *
     * <code>int64 leaf_index = 1;</code>
     * @param value The leafIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLeafIndex(long value) {
      copyOnWrite();
      instance.setLeafIndex(value);
      return this;
    }
    /**
     * <pre>
     * leaf_index indicates the requested leaf index when this message is used for
     * a leaf inclusion proof.  This field is set to zero when this message is
     * used for a consistency proof.
     * </pre>
     *
     * <code>int64 leaf_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeafIndex() {
      copyOnWrite();
      instance.clearLeafIndex();
      return this;
    }

    /**
     * <code>repeated bytes hashes = 3;</code>
     * @return A list containing the hashes.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getHashesList() {
      return java.util.Collections.unmodifiableList(
          instance.getHashesList());
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @return The count of hashes.
     */
    @java.lang.Override
    public int getHashesCount() {
      return instance.getHashesCount();
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @param index The index of the element to return.
     * @return The hashes at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHashes(int index) {
      return instance.getHashes(index);
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @param value The hashes to set.
     * @return This builder for chaining.
     */
    public Builder setHashes(
        int index, com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHashes(index, value);
      return this;
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @param value The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addHashes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addHashes(value);
      return this;
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @param values The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addAllHashes(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      copyOnWrite();
      instance.addAllHashes(values);
      return this;
    }
    /**
     * <code>repeated bytes hashes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashes() {
      copyOnWrite();
      instance.clearHashes();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:trillian.Proof)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new google.trillian.proto.Proof();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "leafIndex_",
            "hashes_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0003\u0002\u0000\u0001\u0000\u0001\u0002\u0003\u001c" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<google.trillian.proto.Proof> parser = PARSER;
        if (parser == null) {
          synchronized (google.trillian.proto.Proof.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<google.trillian.proto.Proof>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:trillian.Proof)
  private static final google.trillian.proto.Proof DEFAULT_INSTANCE;
  static {
    Proof defaultInstance = new Proof();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Proof.class, defaultInstance);
  }

  public static google.trillian.proto.Proof getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Proof> PARSER;

  public static com.google.protobuf.Parser<Proof> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

