// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trillian.proto

package google.trillian.proto;

public interface SignedMapRootOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trillian.SignedMapRoot)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * map_root holds the TLS-serialization of the following structure (described
   * in RFC5246 notation): Clients should validate signature with
   * VerifySignedMapRoot before deserializing map_root.
   * enum { v1(1), (65535)} Version;
   * struct {
   *   opaque root_hash&lt;0..128&gt;;
   *   uint64 timestamp_nanos;
   *   uint64 revision;
   *   opaque metadata&lt;0..65535&gt;;
   * } MapRootV1;
   * struct {
   *   Version version;
   *   select(version) {
   *     case v1: MapRootV1;
   *   }
   * } MapRoot;
   * </pre>
   *
   * <code>bytes map_root = 9;</code>
   * @return The mapRoot.
   */
  com.google.protobuf.ByteString getMapRoot();

  /**
   * <pre>
   * Signature is the raw signature over MapRoot.
   * </pre>
   *
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
